### ISSUE TITLE
Use stable Tailscale release

### ISSUE THREAD

**Issue by Nicols0Mart** [hollie/tailscale-caddy-proxy#5]
Hey man, would be nice if you used "ARG TAILSCALE_VERSION=stable" so you don't have to update the dockerfile every time a new release for tailscale is available.

**Comment by hollie** [comment]
Hey @Nicols0Mart 

I used to do this. Then Tailscale released a docker base image that was causing the clients to re-authenticate. I needed to revert to a previous Tailscale version until this was fixed. 
Since then I always specify a specific version to build my image and test it out before publishing it to docker hub.

I do publish a docker image with stable tag that you can use:

`hollie/tailscale-caddy-proxy:latest`

Kind regards,
 Hollie.
